---
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
    name: mihai
spec:
    groups:
        - system:authenticated
    usages:
        - digital signature
        - key encipherment
        - server auth
    request:
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZiV2xvWVdrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDOGVyUGlMcmJRRkdYTlovZklrYjVCMWxZU2V4dUNXK0YzSzh4MmRiNjBLWGo0ClBiVStaRzlxcmVacHdvVEgvNUNFZTczTTduZzFsd0VHdGJaK3lmK3dPbU9WUGpNd0h3YXJ5cHJacTF6eFhlZmEKRGlzVVRNYWg3N0ZWdzJNTW5pTGp4aWRYZW92NlBDQ21oL0t0dUNKUy9weXpjUEdOLzJpSjVDczFvZmJQRWR2OApLN1JaVmxLUGdvNHpNcWdXM25DZEFJejNUbnZMbkFvYnhBZk9OS3ZpbU5SNnNvZEo5bEYwbStpRUI2VC9BQ3czCjFHK1p4d2MzYWtGb2lra3ZpNFI5RnBGMEJ2K2VaV3Y1R1lUY2tWU2plVjNuVWdtZHlNOXR0TmRheWpaWEZzeEcKV2VDQ2VtTXVVSGdVWEhzVmsrZkUrR2V2S0o2TlcwYkdPS21zNFhDTkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFsa3NWTGhTOWZPYlRlUHgrSUc5SHRXNnJ2Zzc5V09TVjFzb0ZYdFdpS3NZV3RtL2hRWlB2CnNMM3U3clh2dkoyRGMvbXRpaytDRmJQeHl5MTd6cmpFeVU1TU8vVVdWOVRWYldLSWlPUVNjcHBBcE0rWlFYKzIKWDhJS3RDUnBWVmpTaWxpRlVhTmc3S3VKbklna2pPWDJwWWdoTW40UVN2bHZtVUpqR2tFN2pGYkdPNmVhc3RXZApRcGZiK1hzNDhMUE1BT0RZSkJrR3lJa1NPTWFEaUgralFaSE93UFNCbjliT1FjRXVJL1JPaXVOb0MwSm45M3FOCktqYzlTaXRjRmU0TENpZ2hwaHl3ZlhqaTFRM3IzRjgxWUM4WHEzc2NWcm5kMW8wOFJOYWM3MmI1UjJNcjQ0elcKNXBTam1SbEkxclJvbEdGei9aUlUvYnpVK0pYLzlINEJaZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=